//! Parametric KiCad footprint generation.

use anyhow::{bail, Result};
use serde::Serialize;

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct Pad {
    pub name: String,
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
    pub shape: &'static str,
    #[serde(rename = "type")]
    pub pad_type: &'static str,
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct Footprint {
    pub name: String,
    pub description: String,
    pub tags: Vec<String>,
    pub attr: &'static str,
    pub pads: Vec<Pad>,
}

impl Footprint {
    fn smd(name: String, description: String) -> Self {
        Self {
            name,
            description,
            tags: vec![],
            attr: "smd",
            pads: vec![],
        }
    }
    fn tht(name: String, description: String) -> Self {
        Self {
            name,
            description,
            tags: vec![],
            attr: "through_hole",
            pads: vec![],
        }
    }
    fn pad(&mut self, name: impl ToString, x: f64, y: f64, width: f64, height: f64) {
        self.pads.push(Pad {
            name: name.to_string(),
            x,
            y,
            width,
            height,
            shape: "roundrect",
            pad_type: "smd",
        });
    }
    fn th_pad(&mut self, name: impl ToString, x: f64, y: f64, size: f64) {
        self.pads.push(Pad {
            name: name.to_string(),
            x,
            y,
            width: size,
            height: size,
            shape: "circle",
            pad_type: "thru_hole",
        });
    }
    pub fn to_sexp(&self) -> String {
        let mut out = format!("(footprint \"{}\"\n  (version 20240108)\n  (generator kicadmium)\n  (descr \"{}\")\n  (attr {})\n", self.name.replace('"', "\\\""), self.description.replace('"', "\\\""), self.attr);
        for p in &self.pads {
            let layers = if p.pad_type == "smd" {
                "\"F.Cu\" \"F.Paste\" \"F.Mask\""
            } else {
                "\"*.Cu\" \"*.Mask\""
            };
            let drill = if p.pad_type == "thru_hole" {
                format!(" (drill {:.3})", p.width * 0.55)
            } else {
                String::new()
            };
            out.push_str(&format!(
                "  (pad \"{}\" {} {} (at {:.3} {:.3}) (size {:.3} {:.3}){} (layers {}))\n",
                p.name, p.pad_type, p.shape, p.x, p.y, p.width, p.height, drill, layers
            ));
        }
        out.push_str(")\n");
        out
    }
}

pub fn soic(
    pins: usize,
    pitch: Option<f64>,
    body_width: Option<f64>,
    body_length: Option<f64>,
    name: Option<String>,
) -> Result<Footprint> {
    if !(4..=32).contains(&pins) || !pins.is_multiple_of(2) {
        bail!("SOIC pins must be an even number from 4-32");
    }
    let pitch = pitch.unwrap_or(1.27);
    let width = body_width.unwrap_or(if pins <= 16 { 3.9 } else { 7.5 });
    let length = body_length.unwrap_or((pins / 2 - 1) as f64 * pitch + 1.1);
    let mut fp = Footprint::smd(
        name.unwrap_or_else(|| format!("SOIC-{pins}_{width:.1}x{length:.1}mm_P{pitch:.2}mm")),
        format!("SOIC-{pins}, generated by kct"),
    );
    let n = pins / 2;
    let x = width / 2.0 + 0.75;
    for i in 0..n {
        let y = (i as f64 - (n - 1) as f64 / 2.0) * pitch;
        fp.pad(i + 1, -x, y, 1.95, 0.6);
        fp.pad(pins - i, x, y, 1.95, 0.6);
    }
    Ok(fp)
}

pub fn qfp(
    pins: usize,
    pitch: Option<f64>,
    body_size: Option<f64>,
    name: Option<String>,
) -> Result<Footprint> {
    if pins < 8 || !pins.is_multiple_of(4) {
        bail!("QFP pins must be divisible by 4");
    }
    let pitch = pitch.unwrap_or(0.5);
    let body = body_size.unwrap_or(match pins {
        32 | 48 => 7.0,
        44 | 64 => 10.0,
        80 => 12.0,
        100 => 14.0,
        _ => 20.0,
    });
    let mut fp = Footprint::smd(
        name.unwrap_or_else(|| format!("LQFP-{pins}_{body:.1}x{body:.1}mm_P{pitch:.2}mm")),
        format!("LQFP-{pins}, generated by kct"),
    );
    let n = pins / 4;
    let edge = body / 2.0 + 0.5;
    for side in 0..4 {
        for i in 0..n {
            let along = (i as f64 - (n - 1) as f64 / 2.0) * pitch;
            let (x, y, w, h) = match side {
                0 => (along, edge, 0.3, 1.2),
                1 => (edge, -along, 1.2, 0.3),
                2 => (-along, -edge, 0.3, 1.2),
                _ => (-edge, along, 1.2, 0.3),
            };
            fp.pad(side * n + i + 1, x, y, w, h);
        }
    }
    Ok(fp)
}

pub fn qfn(
    pins: usize,
    pitch: Option<f64>,
    body_size: Option<f64>,
    exposed_pad: Option<f64>,
    name: Option<String>,
) -> Result<Footprint> {
    if pins < 8 || !pins.is_multiple_of(4) {
        bail!("QFN pins must be divisible by 4");
    }
    let pitch = pitch.unwrap_or(0.5);
    let body = body_size.unwrap_or(4.0);
    let mut fp = qfp(
        pins,
        Some(pitch),
        Some(body),
        name.or_else(|| {
            Some(format!(
                "QFN-{pins}_{body:.1}x{body:.1}mm_P{pitch:.2}mm{}",
                if exposed_pad.is_some() { "_EP" } else { "" }
            ))
        }),
    )?;
    fp.description = format!("QFN-{pins}, generated by kct");
    let edge = body / 2.0 - 0.2;
    for p in &mut fp.pads {
        if p.x.abs() > p.y.abs() {
            p.x = p.x.signum() * edge;
            p.width = 0.8;
            p.height = 0.3
        } else {
            p.y = p.y.signum() * edge;
            p.width = 0.3;
            p.height = 0.8
        }
    }
    if let Some(ep) = exposed_pad {
        fp.pad(pins + 1, 0.0, 0.0, ep, ep);
    }
    Ok(fp)
}

pub fn chip(size: &str, prefix: &str, metric: bool, name: Option<String>) -> Result<Footprint> {
    let (length, width, pad_w, pad_h, gap, metric_code) = match size {
        "0201" => (0.6, 0.3, 0.4, 0.35, 0.3, "0603"),
        "0402" => (1.0, 0.5, 0.6, 0.55, 0.5, "1005"),
        "0603" => (1.6, 0.8, 0.9, 0.95, 0.8, "1608"),
        "0805" => (2.0, 1.25, 1.0, 1.35, 1.0, "2012"),
        "1206" => (3.2, 1.6, 1.15, 1.8, 1.8, "3216"),
        "1210" => (3.2, 2.5, 1.15, 2.7, 1.8, "3225"),
        "1812" => (4.5, 3.2, 1.3, 3.4, 2.6, "4532"),
        "2010" => (5.0, 2.5, 1.3, 2.7, 3.0, "5025"),
        "2512" => (6.3, 3.2, 1.5, 3.4, 4.0, "6332"),
        _ => bail!("unknown chip size {size}"),
    };
    let code = if metric { metric_code } else { size };
    let base = if prefix.is_empty() { "Chip" } else { prefix };
    let mut fp = Footprint::smd(
        name.unwrap_or_else(|| format!("{base}_{code}_{length:.1}x{width:.1}mm")),
        format!("{size} chip component"),
    );
    let x = (gap + pad_w) / 2.0;
    fp.pad(1, -x, 0.0, pad_w, pad_h);
    fp.pad(2, x, 0.0, pad_w, pad_h);
    Ok(fp)
}

pub fn dip(
    pins: usize,
    pitch: Option<f64>,
    row_spacing: Option<f64>,
    name: Option<String>,
) -> Result<Footprint> {
    if pins < 4 || !pins.is_multiple_of(2) {
        bail!("DIP pins must be even and at least 4")
    }
    let pitch = pitch.unwrap_or(2.54);
    let rows = row_spacing.unwrap_or(7.62);
    let mut fp = Footprint::tht(
        name.unwrap_or_else(|| format!("DIP-{pins}_W{rows:.2}mm_P{pitch:.2}mm")),
        format!("DIP-{pins}"),
    );
    let n = pins / 2;
    for i in 0..n {
        let y = i as f64 * pitch;
        fp.th_pad(i + 1, 0.0, y, 1.6);
        fp.th_pad(pins - i, rows, y, 1.6)
    }
    Ok(fp)
}

pub fn pin_header(
    pins: usize,
    rows: usize,
    pitch: Option<f64>,
    name: Option<String>,
) -> Result<Footprint> {
    if pins == 0 || rows == 0 || !pins.is_multiple_of(rows) {
        bail!("pin count must be divisible by rows")
    }
    let pitch = pitch.unwrap_or(2.54);
    let cols = pins / rows;
    let mut fp = Footprint::tht(
        name.unwrap_or_else(|| format!("PinHeader_{rows}x{cols:02}_P{pitch:.2}mm")),
        format!("{rows}x{cols} pin header"),
    );
    for col in 0..cols {
        for row in 0..rows {
            fp.th_pad(
                col * rows + row + 1,
                row as f64 * pitch,
                col as f64 * pitch,
                1.7,
            )
        }
    }
    Ok(fp)
}

pub fn sot(variant: &str, name: Option<String>) -> Result<Footprint> {
    let (positions, w, h): (&[(f64, f64)], f64, f64) = match variant {
        "SOT-23" => (&[(-0.95, -1.0), (0.95, -1.0), (0.0, 1.0)], 1.0, 0.6),
        "SOT-23-5" => (
            &[
                (-0.95, -1.3),
                (0.0, -1.3),
                (0.95, -1.3),
                (0.95, 1.3),
                (-0.95, 1.3),
            ],
            1.06,
            0.6,
        ),
        "SOT-23-6" => (
            &[
                (-0.95, -1.3),
                (0.0, -1.3),
                (0.95, -1.3),
                (0.95, 1.3),
                (0.0, 1.3),
                (-0.95, 1.3),
            ],
            1.06,
            0.6,
        ),
        "SOT-223" => (
            &[(-2.3, 3.15), (0.0, 3.15), (2.3, 3.15), (0.0, -3.15)],
            1.6,
            0.9,
        ),
        "SOT-89" => (&[(-1.5, 2.05), (0.0, 2.05), (1.5, 2.05)], 1.5, 0.6),
        _ => bail!("unknown SOT variant {variant}"),
    };
    let mut fp = Footprint::smd(
        name.unwrap_or_else(|| variant.to_owned()),
        format!("{variant}, generated by kct"),
    );
    for (i, (x, y)) in positions.iter().enumerate() {
        fp.pad(i + 1, *x, *y, w, h)
    }
    Ok(fp)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn expected_counts() {
        assert_eq!(soic(8, None, None, None, None).unwrap().pads.len(), 8);
        assert_eq!(qfp(48, None, None, None).unwrap().pads.len(), 48);
        assert_eq!(
            qfn(16, None, Some(3.0), Some(1.7), None)
                .unwrap()
                .pads
                .len(),
            17
        );
        assert_eq!(chip("0402", "R", false, None).unwrap().pads.len(), 2);
        assert_eq!(dip(8, None, None, None).unwrap().pads.len(), 8);
        assert_eq!(pin_header(10, 2, None, None).unwrap().pads.len(), 10);
    }
    #[test]
    fn output_is_kicad() {
        let s = soic(8, None, None, None, None).unwrap().to_sexp();
        assert!(s.contains("(footprint"));
        assert!(s.contains("(pad \"1\" smd"));
    }
}
