//! The generated NewStroke table: size, checksum and a few decoded glyphs.

use kicad_strokes::glyphs::{FIRST_CODE_POINT, GLYPHS, GLYPH_COUNT};
use kicad_strokes::{decode_glyph, glyph};
use sha2::{Digest, Sha256};

/// SHA-256 of all glyph strings joined with `\n`, as generated by
/// `examples/gen_glyphs.rs` from the pinned 2015 CC0 tarball. Changes only
/// if `glyphs.rs` is regenerated from a different source.
const TABLE_SHA256: &str = "12204f2db9308bd15c26c51204791f149455118632c7a61960a9896008722236";

#[test]
fn table_covers_u0020_to_u2bff() {
    assert_eq!(GLYPH_COUNT, 11232);
    assert_eq!(GLYPHS.len(), GLYPH_COUNT);
    assert_eq!(FIRST_CODE_POINT, 0x20);
    assert_eq!(FIRST_CODE_POINT as usize + GLYPH_COUNT - 1, 0x2BFF);
}

#[test]
fn table_checksum_is_pinned() {
    let got = format!("{:x}", Sha256::digest(GLYPHS.join("\n").as_bytes()));
    assert_eq!(got, TABLE_SHA256);
}

#[test]
fn every_entry_is_well_formed() {
    for (i, g) in GLYPHS.iter().enumerate() {
        assert!(
            g.len() >= 2 && g.len() % 2 == 0,
            "U+{:04X}: {g:?}",
            i + 0x20
        );
        assert!(g.bytes().all(|b| (b' '..=b'~').contains(&b)));
        let d = decode_glyph(g);
        assert!(d.right >= d.left, "U+{:04X}", i + 0x20);
    }
}

#[test]
fn space_has_advance_and_no_strokes() {
    let g = glyph(' ').unwrap();
    assert_eq!((g.left, g.right), (-8, 8));
    assert!(g.strokes.is_empty());
}

#[test]
fn decodes_h() {
    // "G]L[LF RLPXP RX[XF"
    let g = glyph('H').unwrap();
    assert_eq!((g.left, g.right), (-11, 11));
    assert_eq!(
        g.strokes,
        vec![
            vec![[-6, 9], [-6, -12]],
            vec![[-6, -2], [6, -2]],
            vec![[6, 9], [6, -12]],
        ]
    );
}

#[test]
fn decodes_digit_one_and_escaped_backslash() {
    // U+0031 "H\\X[L[ RR[RFPINKLL": the right bearing is a backslash.
    assert_eq!(GLYPHS[0x31 - 0x20], "H\\X[L[ RR[RFPINKLL");
    let g = glyph('1').unwrap();
    assert_eq!((g.left, g.right), (-10, 10));
    assert_eq!(g.strokes[0], vec![[6, 9], [-6, 9]]);
    assert_eq!(
        g.strokes[1],
        vec![[0, 9], [0, -12], [-2, -9], [-4, -7], [-6, -6]]
    );
}

#[test]
fn tilde_and_ohm_are_the_2015_glyphs() {
    // KiCad later redrew these two; the table must carry the CC0 originals.
    // In 2015, U+2126 OHM SIGN was still the placeholder box (U+03A9 GREEK
    // CAPITAL OMEGA has a real glyph).
    assert_eq!(GLYPHS[0x7E - 0x20], "KZMHNGPFTHVGWF");
    assert_eq!(GLYPHS[0x2126 - 0x20], "F^K[KFYFY[K[");
    assert_ne!(GLYPHS[0x3A9 - 0x20], "F^K[KFYFY[K[");
}

#[test]
fn outside_the_table_is_none() {
    assert!(glyph('\u{1F}').is_none());
    assert!(glyph('\u{2C00}').is_none());
    assert!(glyph('\u{4E2D}').is_none()); // no CJK
}

#[test]
fn placeholder_box_is_u2bff() {
    assert_eq!(GLYPHS[0x2BFF - 0x20], "F^K[KFYFY[K[");
}
