//! Regenerates `kicad-strokes/src/glyphs.rs` from the NewStroke 2015 CC0 release.
//!
//! The only permitted source is the author's release tarball
//! <https://vovanium.ru/_media/sledy/newstroke/newstroke-font.tgz>, SHA-256
//! `dba1c334834e21bdbd15395dc610ecc2bf2eb6675ba0c4585597b375b7bd099e`
//! (see `docs/newstroke-provenance.md`). Extract it and run:
//!
//! ```text
//! cargo run -p kicad-strokes --example gen_glyphs -- \
//!     /path/to/newstroke_font.cpp --tarball /path/to/newstroke-font.tgz \
//!     > kicad-strokes/src/glyphs.rs
//! ```
//!
//! Only the glyph string literals are read; none of the source file's comment
//! or header text is copied. With `--tarball`, the tarball's SHA-256 is checked
//! against the pinned value first.
//!
//! The example links the crate, so it needs a compiling `src/glyphs.rs`; restore
//! the checked-in one from git before regenerating if it is missing or broken.

use sha2::{Digest, Sha256};
use std::fmt::Write as _;

const TARBALL_SHA256: &str = "dba1c334834e21bdbd15395dc610ecc2bf2eb6675ba0c4585597b375b7bd099e";
const GLYPH_COUNT: usize = 11232; // U+0020..=U+2BFF

fn die(msg: &str) -> ! {
    eprintln!("gen_glyphs: {msg}");
    std::process::exit(1)
}

/// Parses the C string literal at the start of `line`.
fn parse_literal(line: &str) -> String {
    let mut out = String::new();
    let mut chars = line.chars();
    if chars.next() != Some('"') {
        die(&format!("expected string literal: {line}"));
    }
    loop {
        match chars.next() {
            Some('"') => return out,
            Some('\\') => match chars.next() {
                Some(c @ ('\\' | '"' | '\'')) => out.push(c),
                other => die(&format!("unsupported escape {other:?} in {line}")),
            },
            Some(c) => out.push(c),
            None => die(&format!("unterminated literal: {line}")),
        }
    }
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let mut cpp = None;
    let mut tarball = None;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        if a == "--tarball" {
            tarball = Some(
                it.next()
                    .unwrap_or_else(|| die("--tarball needs a path"))
                    .clone(),
            );
        } else {
            cpp = Some(a.clone());
        }
    }
    let cpp =
        cpp.unwrap_or_else(|| die("usage: gen_glyphs <newstroke_font.cpp> [--tarball <tgz>]"));
    if let Some(t) = &tarball {
        let bytes = std::fs::read(t).unwrap_or_else(|e| die(&format!("{t}: {e}")));
        let got = format!("{:x}", Sha256::digest(&bytes));
        if got != TARBALL_SHA256 {
            die(&format!("tarball sha256 {got} != pinned {TARBALL_SHA256}"));
        }
    } else {
        eprintln!("gen_glyphs: warning: no --tarball given, source checksum not verified");
    }
    let src = std::fs::read_to_string(&cpp).unwrap_or_else(|e| die(&format!("{cpp}: {e}")));

    // The table is the first `{ ... };` block after `newstroke_font[]`.
    let start = src
        .find("newstroke_font[]")
        .unwrap_or_else(|| die("no newstroke_font[] table"));
    let body = &src[start..];
    let open = body
        .find('{')
        .unwrap_or_else(|| die("no table opening brace"));
    let close = body
        .find("};")
        .unwrap_or_else(|| die("no table closing brace"));
    let glyphs: Vec<String> = body[open + 1..close]
        .lines()
        .map(str::trim_start)
        .filter(|t| t.starts_with('"'))
        .map(parse_literal)
        .collect();
    if glyphs.len() != GLYPH_COUNT {
        die(&format!(
            "found {} glyphs, expected {GLYPH_COUNT}",
            glyphs.len()
        ));
    }

    let mut o = String::new();
    o.push_str(&format!(
        "// @generated by kicad-strokes/examples/gen_glyphs.rs. Do not edit by hand.\n\
         //\n\
         // NewStroke font by Vladimir Uryvaev (vovanium), CC0 1.0, release 2015-11-19,\n\
         // https://vovanium.ru/sledy/newstroke/en, source tarball sha256\n\
         // {TARBALL_SHA256}\n\
         // (https://vovanium.ru/_media/sledy/newstroke/newstroke-font.tgz).\n\
         // Provenance and import rules: docs/newstroke-provenance.md.\n\
         //\n\
         // Regenerate (after checking the tarball):\n\
         //   cargo run -p kicad-strokes --example gen_glyphs -- \\\n\
         //       <extracted>/newstroke_font.cpp --tarball <newstroke-font.tgz> \\\n\
         //       > kicad-strokes/src/glyphs.rs\n\
         //\n\
         // One entry per code point, U+0020..=U+2BFF in order. Encoding: chars 0 and 1\n\
         // are the left and right bearings, then (x, y) coordinate pairs, every value\n\
         // being `c - 'R'`; \" R\" lifts the pen.\n\n\
         /// Number of glyphs in [`GLYPHS`] (U+0020..=U+2BFF).\n\
         pub const GLYPH_COUNT: usize = {GLYPH_COUNT};\n\n\
         /// Code point of `GLYPHS[0]`.\n\
         pub const FIRST_CODE_POINT: u32 = 0x20;\n\n\
         /// NewStroke glyph strings, indexed by `code point - FIRST_CODE_POINT`.\n\
         #[rustfmt::skip]\n\
         pub static GLYPHS: [&str; {GLYPH_COUNT}] = [\n"
    ));
    for (i, g) in glyphs.iter().enumerate() {
        let mut esc = String::with_capacity(g.len());
        for c in g.chars() {
            match c {
                '\\' => esc.push_str("\\\\"),
                '"' => esc.push_str("\\\""),
                c if c.is_ascii_graphic() || c == ' ' => esc.push(c),
                c => die(&format!("non-ASCII glyph data {c:?} at index {i}")),
            }
        }
        let cp = 0x20 + i as u32;
        if cp.is_multiple_of(16) {
            let _ = writeln!(o, "    \"{esc}\", // U+{cp:04X}");
        } else {
            let _ = writeln!(o, "    \"{esc}\",");
        }
    }
    o.push_str("];\n");
    print!("{o}");
}
